class StackMachineInterpreter:
    """
    MiniLang Stack Machine Interpreter.

    Executes the instructions generated by backend.py.

    Supports:
    - Stack operations
    - Variables
    - Arithmetic
    - Comparisons
    - Logical operations
    - Labels
    - GOTO
    - Conditional jump
    - Function calls
    - RETURN
    - Parameters
    """

    def __init__(self, instructions):
        self.instructions = instructions

        self.stack = []
        self.variables = {}

        self.labels = {}
        self.call_stack = []
        self.parameters = []

        self.program_counter = 0

        self.return_value = None

        self.build_label_table()

    # ==================================================
    # Label table
    # ==================================================

    def build_label_table(self):
        for index, instruction in enumerate(
            self.instructions
        ):
            parts = instruction.split()

            if len(parts) >= 2 and parts[0] == "LABEL":
                label = parts[1]

                self.labels[label] = index

    # ==================================================
    # Main execution
    # ==================================================

    def run(self):
        self.program_counter = 0

        while (
            self.program_counter
            < len(self.instructions)
        ):
            instruction = self.instructions[
                self.program_counter
            ].strip()

            if not instruction:
                self.program_counter += 1
                continue

            # Comment
            if instruction.startswith(";"):
                self.program_counter += 1
                continue

            self.execute(instruction)

        return self.return_value

    # ==================================================
    # Execute instruction
    # ==================================================

    def execute(self, instruction):
        parts = instruction.split()

        if not parts:
            self.program_counter += 1
            return

        opcode = parts[0]

        # ----------------------------------------------
        # LABEL
        # ----------------------------------------------

        if opcode == "LABEL":
            self.program_counter += 1
            return

        # ----------------------------------------------
        # LOAD
        # ----------------------------------------------

        if opcode == "LOAD":
            value = instruction[5:].strip()

            self.stack.append(
                self.get_value(value)
            )

            self.program_counter += 1
            return

        # ----------------------------------------------
        # STORE
        # ----------------------------------------------

        if opcode == "STORE":
            variable = instruction[6:].strip()

            if self.stack:
                value = self.stack.pop()
            else:
                value = 0

            self.variables[variable] = value

            self.program_counter += 1
            return

        # ----------------------------------------------
        # Arithmetic
        # ----------------------------------------------

        if opcode in {
            "ADD",
            "SUB",
            "MUL",
            "DIV",
            "MOD"
        }:
            self.execute_arithmetic(opcode)

            self.program_counter += 1
            return

        # ----------------------------------------------
        # Comparison
        # ----------------------------------------------

        if opcode in {
            "EQ",
            "NE",
            "LT",
            "GT",
            "LE",
            "GE"
        }:
            self.execute_comparison(opcode)

            self.program_counter += 1
            return

        # ----------------------------------------------
        # Logical
        # ----------------------------------------------

        if opcode in {
            "AND",
            "OR"
        }:
            self.execute_logical(opcode)

            self.program_counter += 1
            return

        # ----------------------------------------------
        # Unary
        # ----------------------------------------------

        if opcode == "NEG":
            value = self.stack.pop()

            self.stack.append(-value)

            self.program_counter += 1
            return

        if opcode == "NOT":
            value = self.stack.pop()

            self.stack.append(
                0 if value else 1
            )

            self.program_counter += 1
            return

        # ----------------------------------------------
        # GOTO
        # ----------------------------------------------

        if opcode == "GOTO":
            label = parts[1]

            self.jump_to(label)
            return

        # ----------------------------------------------
        # JZ
        # ----------------------------------------------

        if opcode == "JZ":
            label = parts[1]

            condition = self.stack.pop()

            if not condition:
                self.jump_to(label)
            else:
                self.program_counter += 1

            return

        # ----------------------------------------------
        # PARAM
        # ----------------------------------------------

        if opcode == "PARAM":
            if self.stack:
                value = self.stack.pop()

                self.parameters.append(value)

            self.program_counter += 1
            return

        # ----------------------------------------------
        # CALL
        # ----------------------------------------------

        if opcode == "CALL":
            function_name = parts[1]

            argument_count = 0

            if len(parts) >= 3:
                try:
                    argument_count = int(parts[2])
                except ValueError:
                    argument_count = 0

            self.execute_call(
                function_name,
                argument_count
            )

            return

        # ----------------------------------------------
        # RETURN
        # ----------------------------------------------

        if opcode == "RETURN":

            if self.stack:
                value = self.stack.pop()
            else:
                value = 0

            # Returning from a function
            if self.call_stack:

                return_pc = self.call_stack.pop()

                self.stack.append(value)

                self.program_counter = (
                    return_pc
                )

            else:
                # Program-level return
                self.return_value = value

                self.program_counter = (
                    len(self.instructions)
                )

            return

        # Unknown instruction
        self.program_counter += 1

    # ==================================================
    # Arithmetic
    # ==================================================

    def execute_arithmetic(self, opcode):

        if len(self.stack) < 2:
            self.stack.append(0)
            return

        right = self.stack.pop()
        left = self.stack.pop()

        if opcode == "ADD":
            result = left + right

        elif opcode == "SUB":
            result = left - right

        elif opcode == "MUL":
            result = left * right

        elif opcode == "DIV":
            if right == 0:
                raise RuntimeError(
                    "Division by zero."
                )

            result = left // right

        elif opcode == "MOD":
            if right == 0:
                raise RuntimeError(
                    "Modulo by zero."
                )

            result = left % right

        else:
            result = 0

        self.stack.append(result)

    # ==================================================
    # Comparison
    # ==================================================

    def execute_comparison(self, opcode):

        if len(self.stack) < 2:
            self.stack.append(0)
            return

        right = self.stack.pop()
        left = self.stack.pop()

        if opcode == "EQ":
            result = int(left == right)

        elif opcode == "NE":
            result = int(left != right)

        elif opcode == "LT":
            result = int(left < right)

        elif opcode == "GT":
            result = int(left > right)

        elif opcode == "LE":
            result = int(left <= right)

        elif opcode == "GE":
            result = int(left >= right)

        else:
            result = 0

        self.stack.append(result)

    # ==================================================
    # Logical
    # ==================================================

    def execute_logical(self, opcode):

        if len(self.stack) < 2:
            self.stack.append(0)
            return

        right = self.stack.pop()
        left = self.stack.pop()

        if opcode == "AND":
            result = int(
                bool(left) and bool(right)
            )

        else:
            result = int(
                bool(left) or bool(right)
            )

        self.stack.append(result)

    # ==================================================
    # Function call
    # ==================================================

    def execute_call(
        self,
        function_name,
        argument_count
    ):
        label = f"FUNC_{function_name}"

        if label not in self.labels:
            raise RuntimeError(
                f"Function '{function_name}' "
                f"not found."
            )

        # Save return address.
        return_address = (
            self.program_counter + 1
        )

        self.call_stack.append(
            return_address
        )

        # Parameters are currently kept in
        # a separate list.
        #
        # They can be assigned to parameter
        # variables by an extended backend.
        if argument_count > 0:
            function_arguments = []

            for _ in range(argument_count):
                if self.parameters:
                    function_arguments.append(
                        self.parameters.pop()
                    )

            function_arguments.reverse()

        # Jump to function.
        self.program_counter = (
            self.labels[label] + 1
        )

    # ==================================================
    # Jump
    # ==================================================

    def jump_to(self, label):
        if label not in self.labels:
            raise RuntimeError(
                f"Label '{label}' not found."
            )

        self.program_counter = (
            self.labels[label] + 1
        )

    # ==================================================
    # Get value
    # ==================================================

    def get_value(self, value):

        value = value.strip()

        # Integer
        try:
            return int(value)
        except ValueError:
            pass

        # String
        if (
            len(value) >= 2
            and value[0] == '"'
            and value[-1] == '"'
        ):
            return value[1:-1]

        # Boolean
        if value == "true":
            return 1

        if value == "false":
            return 0

        # Variable
        if value in self.variables:
            return self.variables[value]

        # Undefined variable
        return 0

    # ==================================================
    # Display state
    # ==================================================

    def print_state(self):
        print("\nInterpreter State:")
        print("-----------------")

        if not self.variables:
            print("No variables.")

        else:
            for name, value in self.variables.items():
                print(
                    f"{name} = {value}"
                )

        print(
            f"Stack = {self.stack}"
        )

        if self.return_value is not None:
            print(
                f"Return value = "
                f"{self.return_value}"
            )
